import { describe, it, expect, vi, beforeEach } from 'vitest'

// ============================================================================
// Mocks
// ============================================================================

let fsStore: Record<string, string> = {}

vi.mock('fs', () => ({
  default: {
    existsSync: vi.fn((filePath: string) => filePath in fsStore),
    mkdirSync: vi.fn(),
    readFileSync: vi.fn((filePath: string) => {
      if (filePath in fsStore) return fsStore[filePath]
      throw new Error(`ENOENT: no such file or directory, open '${filePath}'`)
    }),
    writeFileSync: vi.fn((filePath: string, data: string) => {
      fsStore[filePath] = data
    }),
    renameSync: vi.fn((oldPath: string, newPath: string) => {
      // Atomic write: move temp file to final path
      if (oldPath in fsStore) {
        fsStore[newPath] = fsStore[oldPath]
        delete fsStore[oldPath]
      }
    }),
    unlinkSync: vi.fn((filePath: string) => {
      delete fsStore[filePath]
    }),
  },
}))

let uuidCounter = 0
vi.mock('uuid', () => ({
  v4: vi.fn(() => {
    uuidCounter++
    // Produce valid UUID-format strings so docsFilePath validation (CC-001) accepts them
    const hex = uuidCounter.toString(16).padStart(12, '0')
    return `00000000-0000-4000-a000-${hex}`
  }),
}))

vi.mock('@/lib/file-lock', () => ({
  withLock: vi.fn((_name: string, fn: () => unknown) => Promise.resolve(fn())),
}))

// Mock governance module - getManagerId returns null (no manager configured) for document tests
vi.mock('@/lib/governance', () => ({
  getManagerId: vi.fn(() => null),
  isManager: vi.fn(() => false),
  loadGovernance: vi.fn(() => ({ managerId: null, passwordHash: null, createdAt: null, updatedAt: null })),
  verifyPassword: vi.fn(() => false),
}))

// Mock team-acl module - checkTeamAccess allows all access by default in document tests
vi.mock('@/lib/team-acl', () => ({
  checkTeamAccess: vi.fn(() => ({ allowed: true })),
}))

// Mock agent-registry module - loadAgents returns empty array for document tests
vi.mock('@/lib/agent-registry', () => ({
  loadAgents: vi.fn(() => []),
}))

// Mock validation module - isValidUuid accepts synthetic test UUIDs
vi.mock('@/lib/validation', () => ({
  isValidUuid: vi.fn(() => true),
}))

// Mock agent-auth module - authenticateFromRequest returns system-owner (no agentId) for document tests
vi.mock('@/lib/agent-auth', () => ({
  authenticateFromRequest: vi.fn(() => ({})),
  authenticateAgent: vi.fn(() => ({})),
}))

// Note: team-registry is tested via its real implementation with a mocked 'fs' module.
// This is an integration test pattern — the fs mock is picked up transitively.

// ============================================================================
// Imports (after mocks)
// ============================================================================

import { createTeam } from '@/lib/team-registry'
import { createDocument, loadDocuments } from '@/lib/document-registry'
import { GET as listDocuments, POST as createDocumentRoute } from '@/app/api/teams/[id]/documents/route'
import { GET as getDocumentRoute, PUT as updateDocumentRoute, DELETE as deleteDocumentRoute } from '@/app/api/teams/[id]/documents/[docId]/route'
import { NextRequest } from 'next/server'

// ============================================================================
// Helpers
// ============================================================================

// Valid UUID format that will never be generated by the counter mock -- used for "does not exist" tests
const MISSING_TEAM_ID = 'aaaaaaaa-bbbb-4ccc-9ddd-eeeeeeeeeeee'
const MISSING_DOC_ID = 'ffffffff-eeee-4ddd-9ccc-bbbbbbbbbbbb'

function makeRequest(url: string, options: Record<string, unknown> = {}): NextRequest {
  return new NextRequest(new URL(url, 'http://localhost:23000'), options as any)
}

function makeParams(id: string, docId?: string) {
  if (docId) {
    return { params: Promise.resolve({ id, docId }) }
  }
  return { params: Promise.resolve({ id }) }
}

// ============================================================================
// Setup
// ============================================================================

beforeEach(() => {
  fsStore = {}
  uuidCounter = 0
  vi.clearAllMocks()
})

// ============================================================================
// GET /api/teams/[id]/documents - List documents
// ============================================================================

describe('GET /api/teams/[id]/documents', () => {
  it('returns 404 when team does not exist', async () => {
    const req = makeRequest(`/api/teams/${MISSING_TEAM_ID}/documents`)
    const res = await listDocuments(req, makeParams(MISSING_TEAM_ID) as any)

    expect(res.status).toBe(404)
    const data = await res.json()
    expect(data.error).toBe('Team not found')
  })

  it('returns empty documents array for team with no docs', async () => {
    const team = await createTeam({ name: 'Test Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents`)
    const res = await listDocuments(req, makeParams(team.id) as any)

    expect(res.status).toBe(200)
    const data = await res.json()
    expect(data.documents).toEqual([])
  })

  it('returns documents for a team', async () => {
    const team = await createTeam({ name: 'Docs Team', agentIds: [] })
    await createDocument({ teamId: team.id, title: 'Doc 1', content: 'Content 1' })
    await createDocument({ teamId: team.id, title: 'Doc 2', content: 'Content 2' })

    const req = makeRequest(`/api/teams/${team.id}/documents`)
    const res = await listDocuments(req, makeParams(team.id) as any)

    expect(res.status).toBe(200)
    const data = await res.json()
    expect(data.documents).toHaveLength(2)
    expect(data.documents[0].title).toBe('Doc 1')
    expect(data.documents[1].title).toBe('Doc 2')
  })
})

// ============================================================================
// POST /api/teams/[id]/documents - Create document
// ============================================================================

describe('POST /api/teams/[id]/documents', () => {
  it('returns 404 when team does not exist', async () => {
    const req = makeRequest(`/api/teams/${MISSING_TEAM_ID}/documents`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'Test', content: 'body' }),
    })
    const res = await createDocumentRoute(req, makeParams(MISSING_TEAM_ID) as any)

    expect(res.status).toBe(404)
  })

  it('returns 400 when title is missing', async () => {
    const team = await createTeam({ name: 'Test Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: 'body' }),
    })
    const res = await createDocumentRoute(req, makeParams(team.id) as any)

    expect(res.status).toBe(400)
    const data = await res.json()
    expect(data.error).toBe('title is required')
  })

  it('creates a document with 201 status', async () => {
    const team = await createTeam({ name: 'Create Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'New Doc', content: 'Hello world', pinned: true, tags: ['api'] }),
    })
    const res = await createDocumentRoute(req, makeParams(team.id) as any)

    expect(res.status).toBe(201)
    const data = await res.json()
    expect(data.document.title).toBe('New Doc')
    expect(data.document.content).toBe('Hello world')
    expect(data.document.pinned).toBe(true)
    expect(data.document.tags).toEqual(['api'])
  })

  it('persists created document', async () => {
    const team = await createTeam({ name: 'Persist Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'Persisted', content: 'data' }),
    })
    await createDocumentRoute(req, makeParams(team.id) as any)

    const docs = loadDocuments(team.id)
    expect(docs).toHaveLength(1)
    expect(docs[0].title).toBe('Persisted')
  })

  // SECURITY: Stored XSS risk -- API stores values verbatim; frontend MUST sanitize before rendering.
  // Phase 2: Add server-side HTML sanitization for document titles and content.
  it('stores HTML content verbatim without sanitization (known security surface)', async () => {
    const team = await createTeam({ name: 'XSS Team', agentIds: [] })
    const xssTitle = '<script>alert(1)</script>'

    const req = makeRequest(`/api/teams/${team.id}/documents`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: xssTitle, content: '<img onerror="alert(2)" src=x>' }),
    })
    const res = await createDocumentRoute(req, makeParams(team.id) as any)

    expect(res.status).toBe(201)
    const data = await res.json()
    // API stores values verbatim — this is a known stored-XSS security surface; frontend MUST sanitize before rendering
    expect(data.document.title).toBe(xssTitle)
    expect(data.document.content).toBe('<img onerror="alert(2)" src=x>')

    // Verify persistence also stores verbatim
    const docs = loadDocuments(team.id)
    expect(docs[0].title).toBe(xssTitle)
  })

  it('defaults content to empty string when not provided', async () => {
    const team = await createTeam({ name: 'Default Content', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'No Content' }),
    })
    const res = await createDocumentRoute(req, makeParams(team.id) as any)

    expect(res.status).toBe(201)
    const data = await res.json()
    expect(data.document.content).toBe('')
  })
})

// ============================================================================
// GET /api/teams/[id]/documents/[docId] - Get single document
// ============================================================================

describe('GET /api/teams/[id]/documents/[docId]', () => {
  it('returns 404 when team does not exist', async () => {
    const req = makeRequest(`/api/teams/${MISSING_TEAM_ID}/documents/${MISSING_DOC_ID}`)
    const res = await getDocumentRoute(req, makeParams(MISSING_TEAM_ID, MISSING_DOC_ID) as any)

    expect(res.status).toBe(404)
    const data = await res.json()
    expect(data.error).toBe('Team not found')
  })

  it('returns 404 when document does not exist', async () => {
    const team = await createTeam({ name: 'Test Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents/${MISSING_DOC_ID}`)
    const res = await getDocumentRoute(req, makeParams(team.id, MISSING_DOC_ID) as any)

    expect(res.status).toBe(404)
    const data = await res.json()
    expect(data.error).toBe('Document not found')
  })

  it('returns the document when it exists', async () => {
    const team = await createTeam({ name: 'Get Team', agentIds: [] })
    const doc = await createDocument({ teamId: team.id, title: 'Find Me', content: 'Here I am' })

    const req = makeRequest(`/api/teams/${team.id}/documents/${doc.id}`)
    const res = await getDocumentRoute(req, makeParams(team.id, doc.id) as any)

    expect(res.status).toBe(200)
    const data = await res.json()
    expect(data.document.title).toBe('Find Me')
    expect(data.document.content).toBe('Here I am')
  })
})

// ============================================================================
// PUT /api/teams/[id]/documents/[docId] - Update document
// ============================================================================

describe('PUT /api/teams/[id]/documents/[docId]', () => {
  it('returns 404 when document does not exist', async () => {
    const team = await createTeam({ name: 'Missing Doc Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents/${MISSING_DOC_ID}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'Updated' }),
    })
    const res = await updateDocumentRoute(req, makeParams(team.id, MISSING_DOC_ID) as any)

    expect(res.status).toBe(404)
  })

  it('returns 404 with "Team not found" when team does not exist', async () => {
    /** PUT now validates UUID format (CC-002) and checks team existence (CC-005)
     *  before attempting to update the document. */
    const req = makeRequest(`/api/teams/${MISSING_TEAM_ID}/documents/${MISSING_DOC_ID}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'Updated' }),
    })
    const res = await updateDocumentRoute(req, makeParams(MISSING_TEAM_ID, MISSING_DOC_ID) as any)

    expect(res.status).toBe(404)
    const data = await res.json()
    expect(data.error).toBe('Team not found')
  })

  it('updates document title', async () => {
    const team = await createTeam({ name: 'Update Team', agentIds: [] })
    const doc = await createDocument({ teamId: team.id, title: 'Original', content: '' })

    const req = makeRequest(`/api/teams/${team.id}/documents/${doc.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'Updated Title' }),
    })
    const res = await updateDocumentRoute(req, makeParams(team.id, doc.id) as any)

    expect(res.status).toBe(200)
    const data = await res.json()
    expect(data.document.title).toBe('Updated Title')
  })

  it('updates document content', async () => {
    const team = await createTeam({ name: 'Content Team', agentIds: [] })
    const doc = await createDocument({ teamId: team.id, title: 'Stable', content: 'old' })

    const req = makeRequest(`/api/teams/${team.id}/documents/${doc.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: 'new content' }),
    })
    const res = await updateDocumentRoute(req, makeParams(team.id, doc.id) as any)

    const data = await res.json()
    expect(data.document.content).toBe('new content')
    expect(data.document.title).toBe('Stable')
  })

  it('updates pinned status', async () => {
    const team = await createTeam({ name: 'Pin Team', agentIds: [] })
    const doc = await createDocument({ teamId: team.id, title: 'Pin Me', content: '' })

    const req = makeRequest(`/api/teams/${team.id}/documents/${doc.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ pinned: true }),
    })
    const res = await updateDocumentRoute(req, makeParams(team.id, doc.id) as any)

    const data = await res.json()
    expect(data.document.pinned).toBe(true)
  })

  it('updates document tags', async () => {
    const team = await createTeam({ name: 'Tags Team', agentIds: [] })
    const doc = await createDocument({ teamId: team.id, title: 'Tag Me', content: '', tags: ['old-tag'] })

    const req = makeRequest(`/api/teams/${team.id}/documents/${doc.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ tags: ['new-tag', 'another-tag'] }),
    })
    const res = await updateDocumentRoute(req, makeParams(team.id, doc.id) as any)

    expect(res.status).toBe(200)
    const data = await res.json()
    expect(data.document.tags).toEqual(['new-tag', 'another-tag'])
    // Title and content remain unchanged
    expect(data.document.title).toBe('Tag Me')
    expect(data.document.content).toBe('')
  })
})

// ============================================================================
// DELETE /api/teams/[id]/documents/[docId] - Delete document
// ============================================================================

describe('DELETE /api/teams/[id]/documents/[docId]', () => {
  it('returns 404 when document does not exist', async () => {
    const team = await createTeam({ name: 'Delete Missing Team', agentIds: [] })

    const req = makeRequest(`/api/teams/${team.id}/documents/${MISSING_DOC_ID}`, { method: 'DELETE' })
    const res = await deleteDocumentRoute(req, makeParams(team.id, MISSING_DOC_ID) as any)

    expect(res.status).toBe(404)
  })

  it('returns 404 with "Team not found" when team does not exist', async () => {
    /** DELETE now validates UUID format (CC-002) and checks team existence (CC-006)
     *  before attempting to delete the document. */
    const req = makeRequest(`/api/teams/${MISSING_TEAM_ID}/documents/${MISSING_DOC_ID}`, { method: 'DELETE' })
    const res = await deleteDocumentRoute(req, makeParams(MISSING_TEAM_ID, MISSING_DOC_ID) as any)

    expect(res.status).toBe(404)
    const data = await res.json()
    expect(data.error).toBe('Team not found')
  })

  it('deletes document and returns success', async () => {
    const team = await createTeam({ name: 'Delete Team', agentIds: [] })
    const doc = await createDocument({ teamId: team.id, title: 'Delete Me', content: '' })

    const req = makeRequest(`/api/teams/${team.id}/documents/${doc.id}`, { method: 'DELETE' })
    const res = await deleteDocumentRoute(req, makeParams(team.id, doc.id) as any)

    expect(res.status).toBe(200)
    const data = await res.json()
    expect(data.success).toBe(true)

    const remaining = loadDocuments(team.id)
    expect(remaining).toHaveLength(0)
  })
})
