/**
 * Role-Plugin Service
 *
 * Converts .agent.toml profiles into Claude Code plugins, manages a local
 * marketplace at ~/agents/role-plugins/, and installs plugins into agent
 * working directories with --scope local.
 *
 * The local marketplace trick: Claude Code requires plugins to come from
 * registered marketplaces. We create a directory-based marketplace and
 * register it in settings.local.json via extraKnownMarketplaces. Each
 * agent then enables only its own role-plugin via a project-level
 * .claude/settings.local.json (equivalent to --scope local).
 *
 * IMPORTANT: This local marketplace mechanism is designed EXCLUSIVELY for
 * role-plugins generated by Haephestos or the AI Maestro API. It is NOT a
 * general-purpose plugin installation method. Regular plugins should always
 * be installed from GitHub-hosted marketplaces.
 *
 * GOVERNANCE → ROLE-PLUGIN BINDING RULES:
 *
 * Title MANAGER → MUST use ai-maestro-assistant-manager-agent (auto-installed)
 * Title CHIEF-OF-STAFF → MUST use ai-maestro-chief-of-staff (auto-installed)
 * Title MEMBER → can use any role-plugin (user choice)
 *
 * Auto-installation triggers:
 * 1. POST /api/governance/manager — assigns MANAGER → installs plugin
 * 2. POST /api/teams/{id}/chief-of-staff — assigns COS → installs plugin
 * 3. POST /api/teams (type=closed, chiefOfStaffId) — creates team + COS → installs plugin
 *
 * Role-plugins from marketplace: installed via `claude plugin install <name>@ai-maestro-plugins --scope local`
 *   Claude CLI handles cloning, caching (~/.claude/plugins/cache/), and settings.local.json
 * Custom role-plugins: installed from ~/agents/role-plugins/ local marketplace via settings.local.json
 *
 * Agents (MANAGER, COS) can create MEMBER agents and assign role-plugins via:
 *   aimaestro-agent.sh plugin install <agent> <plugin>@<marketplace> --scope local
 */

import { parse as parseToml } from 'smol-toml'
// Internal import for functions used by createPersona() — also re-exported below for callers
import {
  installPluginLocally as _installPluginLocally,
} from '@/services/element-management-service'
import { join } from 'path'
import { homedir } from 'os'
import { mkdir, writeFile, readFile, readdir, rm, stat } from 'fs/promises'
import { existsSync } from 'fs'
import { execFile } from 'child_process'
import { promisify } from 'util'
import {
  MARKETPLACE_NAME as GITHUB_MARKETPLACE_NAME_IMPORT,
  MARKETPLACE_REPO,
  LOCAL_MARKETPLACE_NAME,
  getLocalMarketplacePath,
  PREDEFINED_ROLE_PLUGIN_NAMES,
  ROLE_PLUGIN_MAIN_AGENTS,
  PLUGIN_COMPATIBLE_TITLES,
} from '@/lib/ecosystem-constants'

const execFileAsync = promisify(execFile)

// ── Paths (derived from ecosystem-constants) ────────────────
const HOME = homedir()
const ROLE_PLUGINS_DIR = getLocalMarketplacePath()
const MARKETPLACE_META_DIR = join(ROLE_PLUGINS_DIR, '.claude-plugin')
const MARKETPLACE_JSON = join(MARKETPLACE_META_DIR, 'marketplace.json')
const PLUGINS_DIR = ROLE_PLUGINS_DIR  // Plugins live directly under ~/agents/role-plugins/<name>/
const CLAUDE_DIR = join(HOME, '.claude')
// User-global Claude Code settings. NOT settings.local.json — that file only
// exists inside a project directory. At the user-home level, Claude Code uses
// settings.json. Writing to ~/.claude/settings.local.json creates a phantom
// file that Claude CLI never reads (see BUG-POLLUTION-001).
const USER_GLOBAL_SETTINGS = join(CLAUDE_DIR, 'settings.json')
const INSTALLED_FILE = join(CLAUDE_DIR, 'plugins', 'installed_plugins.json')

// GitHub marketplace for predefined role plugins (from ecosystem-constants)
// Role-plugins are NOT auto-installed. They are installed ON-DEMAND when a user selects one
// from the dropdown. syncDefaultRolePlugins() only ensures the marketplace is registered.
export const GITHUB_MARKETPLACE_NAME = GITHUB_MARKETPLACE_NAME_IMPORT
const GITHUB_MARKETPLACE_DIR = join(HOME, '.claude', 'plugins', 'marketplaces', GITHUB_MARKETPLACE_NAME)
const GITHUB_MARKETPLACE_MANIFEST = join(GITHUB_MARKETPLACE_DIR, '.claude-plugin', 'marketplace.json')

// The names of the 7 predefined role plugins. Re-exported from ecosystem-constants.
// These are NOT installed at user scope — they are installed on-demand with --scope local.
export const DEFAULT_ROLE_PLUGIN_NAMES: string[] = [...PREDEFINED_ROLE_PLUGIN_NAMES]

// ── AI Maestro compatibility skill content (auto-injected into generated role-plugins) ──

const AIM_GOVERNANCE_RULES_SKILL = `---
name: aim-governance-rules
description: AI Maestro governance rules — 7-title model, messaging matrix, kanban authority, team membership. Auto-injected into all AI Maestro role-plugins.
license: Apache-2.0
compatibility: Requires AI Maestro running on localhost:23000
metadata:
  author: AI Maestro
  version: 1.0.0
context: fork
user-invocable: false
---

# AI Maestro Governance Rules

## 7 Governance Titles

| Title | Plugin | Kanban | Messaging |
|-------|--------|--------|-----------|
| MANAGER | ai-maestro-assistant-manager-agent | Secondary | Direct to all |
| CHIEF-OF-STAFF | ai-maestro-chief-of-staff | Secondary | Direct to team + Manager |
| ORCHESTRATOR | ai-maestro-orchestrator-agent | **Primary** | Direct to team + Manager |
| ARCHITECT | ai-maestro-architect-agent | View only | Team + COS + Orchestrator |
| INTEGRATOR | ai-maestro-integrator-agent | View only | Team + COS + Orchestrator |
| MEMBER | (any role-plugin) | View only | Team + COS + Orchestrator |
| AUTONOMOUS | None (default) | View only | N/A (no team) |

## Rules

1. All teams are **closed** — external messages route through COS
2. Each agent belongs to **at most one team**
3. COS must have a team. MANAGER is usually teamless
4. ORCHESTRATOR is the **primary kanban manager** for the team
5. Team creation requires governance password and auto-creates COS
6. Title changes require governance password

## Messaging Matrix

| From \\\\ To | MANAGER | COS | ORCHESTRATOR | MEMBER |
|-----------|---------|-----|-------------|--------|
| MANAGER | — | Direct | Direct | Via COS |
| COS | Direct | — | Direct | Direct (own team) |
| ORCHESTRATOR | Direct | Direct | — | Direct (own team) |
| MEMBER | Via COS | Direct | Direct | Direct (teammates) |

## Task Reporting

- Report completion: \\\`amp-task-done.sh "message"\\\`
- Report blocker: \\\`amp-task-blocked.sh "reason"\\\`
- Both auto-route to the team's ORCHESTRATOR
`

const AIM_AGENT_OPERATIONS_SKILL = `---
name: aim-agent-operations
description: AI Maestro agent operations — multi-repo management, folder structure, AMP scripts, subagent rules, CI/CD. Auto-injected into all AI Maestro role-plugins.
license: Apache-2.0
compatibility: Requires AI Maestro running on localhost:23000 and gh CLI
metadata:
  author: AI Maestro
  version: 1.0.0
context: fork
user-invocable: false
---

# AI Maestro Agent Operations

## Folder Structure

All repos cloned INSIDE your agent folder. NEVER write outside it.

\\\`\\\`\\\`
~/agents/<persona-name>/
  repos/<repo-1>/        # cloned git repos
  repos/<repo-2>/
  reports/               # subagent reports
  tmp/                   # temp files (NOT /tmp/)
\\\`\\\`\\\`

## Multi-Repo Rules

- Every \\\`git\\\` command MUST use \\\`git -C "$REPO_PATH"\\\`
- Every \\\`gh\\\` command MUST use \\\`--repo "$OWNER/$REPO"\\\`
- NEVER write to /tmp/, ~/.aimaestro/, or outside agent folder
- Determine target repo BEFORE any operation

## AMP Scripts (installed at ~/.local/bin/)

| Script | Purpose |
|--------|---------|
| \\\`amp-project-info.sh\\\` | Show team/project info |
| \\\`amp-project-repos.sh\\\` | List project repositories |
| \\\`amp-clone-repo.sh <url>\\\` | Clone repo to agent folder |
| \\\`amp-list-local-repos.sh\\\` | List locally cloned repos |
| \\\`amp-create-branch.sh <repo> <name>\\\` | Create and push branch |
| \\\`amp-submit-pr.sh <repo> <title>\\\` | Create pull request |
| \\\`amp-task-done.sh <message>\\\` | Report task completion |
| \\\`amp-task-blocked.sh <reason>\\\` | Report blocker |
| \\\`amp-kanban-create-task.sh <title>\\\` | Create kanban task |
| \\\`amp-kanban-move.sh <id> <status>\\\` | Move kanban card |
| \\\`amp-kanban-list.sh\\\` | List kanban items |

## Task Workflow

1. Receive task from Orchestrator (via AMP message)
2. \\\`amp-project-repos.sh\\\` — identify target repo
3. \\\`amp-clone-repo.sh <url>\\\` — clone if needed
4. \\\`amp-create-branch.sh <repo> feature/<desc>\\\` — create branch
5. Implement changes (NEVER on main branch)
6. Run tests
7. \\\`amp-submit-pr.sh <repo> "<title>"\\\` — submit PR
8. \\\`amp-task-done.sh "PR #N submitted"\\\` — report to Orchestrator

## Subagent Rules

When delegating to subagents, ALWAYS include:
- Target repo path: \\\`$AGENT_DIR/repos/<repo-name>\\\`
- Report output: \\\`$AGENT_DIR/reports/<task>.md\\\`
`

/**
 * Inject AI Maestro compatibility skills into a role-plugin.
 * Creates skills/aim-governance-rules/SKILL.md and skills/aim-agent-operations/SKILL.md.
 * Idempotent: overwrites if skills already exist.
 */
export async function injectAiMaestroSkills(pluginDir: string): Promise<string[]> {
  const skillsDir = join(pluginDir, 'skills')

  const govDir = join(skillsDir, 'aim-governance-rules')
  await mkdir(govDir, { recursive: true })
  await writeFile(join(govDir, 'SKILL.md'), AIM_GOVERNANCE_RULES_SKILL)

  const opsDir = join(skillsDir, 'aim-agent-operations')
  await mkdir(opsDir, { recursive: true })
  await writeFile(join(opsDir, 'SKILL.md'), AIM_AGENT_OPERATIONS_SKILL)

  return ['aim-governance-rules', 'aim-agent-operations']
}

// ── Types ──────────────────────────────────────────────────

interface TomlAgent {
  name: string
  program?: string
  model?: string
  workingDirectory?: string
  description?: string
  teamId?: string
  compatibleTitles?: string[]  // Which governance titles can use this plugin
  compatibleClients?: string[]  // Which AI clients can use this plugin (e.g. claude-code, codex)
}

interface TomlSkills {
  primary?: string[]
  secondary?: string[]
  specialized?: string[]
}

interface TomlDependencies {
  plugins?: string[]
  skills?: string[]
  rules?: string[]
  agents?: string[]
  commands?: string[]
  hooks?: string[]
  mcp_servers?: string[]
  lsp_servers?: string[]
  output_styles?: string[]
  tools?: string[]
  frameworks?: string[]
}

interface TomlRules {
  items?: string[]
  recommended?: string[]
}

interface TomlRecommended {
  recommended?: string[]
}

interface ParsedToml {
  agent: TomlAgent
  skills?: TomlSkills
  dependencies?: TomlDependencies
  rules?: TomlRules
  agents?: TomlRecommended
  commands?: TomlRecommended
  hooks?: TomlRecommended
  mcp?: TomlRecommended
  lsp?: TomlRecommended
  output_styles?: TomlRecommended
  description?: { text?: string }
}

export interface RolePlugin {
  name: string
  version: string
  description: string
  model?: string
  program?: string
  pluginDir: string
  source?: 'marketplace' | 'local'
  marketplace?: string
  compatibleTitles?: string[]  // Which governance titles can use this plugin
  compatibleClients?: string[]  // Which AI clients can use this plugin (e.g. claude-code, codex)
}

// ── JSON helpers ───────────────────────────────────────────

async function loadJsonSafe(path: string): Promise<Record<string, unknown>> {
  if (!existsSync(path)) return {}
  try {
    const raw = await readFile(path, 'utf-8')
    return JSON.parse(raw)
  } catch {
    return {}
  }
}

async function saveJsonSafe(path: string, data: Record<string, unknown>): Promise<void> {
  const dir = join(path, '..')
  await mkdir(dir, { recursive: true })
  await writeFile(path, JSON.stringify(data, null, 2) + '\n', 'utf-8')
}

// ── TOML parsing ───────────────────────────────────────────

function parseAgentToml(tomlContent: string): ParsedToml {
  const parsed = parseToml(tomlContent) as Record<string, unknown>

  const agentSection = (parsed.agent || {}) as Record<string, unknown>
  if (!agentSection.name || typeof agentSection.name !== 'string') {
    throw new Error('TOML must have [agent] section with a name field')
  }

  // Parse compatible-titles (array or comma-separated string)
  let compatibleTitles: string[] | undefined
  const rawCompatibleTitles = agentSection['compatible-titles']
  if (rawCompatibleTitles !== undefined) {
    if (Array.isArray(rawCompatibleTitles)) {
      compatibleTitles = (rawCompatibleTitles as unknown[])
        .map(s => String(s).trim().toUpperCase())
        .filter(Boolean)
    } else if (typeof rawCompatibleTitles === 'string') {
      compatibleTitles = rawCompatibleTitles
        .split(',')
        .map(s => s.trim().toUpperCase())
        .filter(Boolean)
    }
  }

  // Parse compatible-clients (array or comma-separated string)
  let compatibleClients: string[] | undefined
  const rawCompatibleClients = agentSection['compatible-clients']
  if (rawCompatibleClients !== undefined) {
    if (Array.isArray(rawCompatibleClients)) {
      compatibleClients = (rawCompatibleClients as unknown[])
        .map(s => String(s).trim().toLowerCase())
        .filter(Boolean)
    } else if (typeof rawCompatibleClients === 'string') {
      compatibleClients = rawCompatibleClients
        .split(',')
        .map(s => s.trim().toLowerCase())
        .filter(Boolean)
    }
  }

  return {
    agent: {
      name: agentSection.name as string,
      program: (agentSection.program as string) || 'claude-code',
      model: agentSection.model as string | undefined,
      workingDirectory: agentSection.workingDirectory as string | undefined,
      description: agentSection.description as string | undefined,
      teamId: agentSection.teamId as string | undefined,
      compatibleTitles,
      compatibleClients,
    },
    skills: parsed.skills as TomlSkills | undefined,
    dependencies: parsed.dependencies as TomlDependencies | undefined,
    rules: parsed.rules as TomlRules | undefined,
    agents: parsed.agents as TomlRecommended | undefined,
    commands: parsed.commands as TomlRecommended | undefined,
    hooks: parsed.hooks as TomlRecommended | undefined,
    mcp: parsed.mcp as TomlRecommended | undefined,
    lsp: parsed.lsp as TomlRecommended | undefined,
    output_styles: parsed.output_styles as TomlRecommended | undefined,
    description: parsed.description as { text?: string } | undefined,
  }
}

// ── Plugin generation ──────────────────────────────────────

/**
 * Generate a Claude Code plugin from a .agent.toml profile.
 * Saves it to ~/agents/role-plugins/<name>/
 */
export async function generatePluginFromToml(
  tomlContent: string,
  agentDescription?: string,
): Promise<{ pluginName: string; pluginDir: string; mainAgentName: string }> {
  const config = parseAgentToml(tomlContent)
  const { agent } = config
  const pluginName = agent.name

  // Validate plugin name to prevent path traversal
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(pluginName)) {
    throw new Error(`Invalid agent name "${pluginName}": must be alphanumeric with hyphens/underscores, no path separators`)
  }

  // Ensure compatible-titles is always set — plugins without it are invalid
  if (!agent.compatibleTitles || agent.compatibleTitles.length === 0) {
    agent.compatibleTitles = ['AUTONOMOUS']
  }
  // Ensure compatible-clients defaults to claude-code if not set
  if (!agent.compatibleClients || agent.compatibleClients.length === 0) {
    agent.compatibleClients = ['claude-code']
  }

  const pluginDir = join(PLUGINS_DIR, pluginName)

  // Wipe existing plugin dir if it exists (regenerating)
  if (existsSync(pluginDir)) {
    await rm(pluginDir, { recursive: true })
  }

  // Create plugin directory structure
  const metaDir = join(pluginDir, '.claude-plugin')
  const agentsDir = join(pluginDir, 'agents')
  await mkdir(metaDir, { recursive: true })
  await mkdir(agentsDir, { recursive: true })

  // 1. plugin.json — prefer [description].text, fall back to [agent].description
  const pluginDescription = config.description?.text || agent.description || `Role plugin for ${pluginName}`
  const pluginJson = {
    name: pluginName,
    version: '1.0.0',
    description: pluginDescription,
  }
  await writeFile(join(metaDir, 'plugin.json'), JSON.stringify(pluginJson, null, 2) + '\n')

  // 2. agents/<plugin-name>-main-agent.md — the persona file
  // Follows the quad-match rule from the SKILL.md: agents/<plugin-name>-main-agent.md
  const mainAgentName = `${pluginName}-main-agent`
  const personaMd = buildPersonaMarkdown(mainAgentName, agent, config, agentDescription)
  await writeFile(join(agentsDir, `${mainAgentName}.md`), personaMd)

  // 3. Rules are NOT copied into the plugin.
  // Global rules (~/.claude/rules/) are auto-loaded by Claude Code for every session.
  // Project-level rules (.claude/rules/) are auto-loaded per project.
  // The [rules].recommended section in the TOML is metadata only (records which
  // rules the PSS profiler selected). No file copying needed — the plugin
  // installation with --scope local handles everything automatically.

  // 4. Save the .agent.toml inside the plugin (quad-match: <plugin-name>.agent.toml)
  //    Haephestos is responsible for adding compatible-titles and compatible-clients
  //    to the TOML BEFORE calling this API. The API saves what it receives as-is.
  await writeFile(join(pluginDir, `${pluginName}.agent.toml`), tomlContent)

  // 5. Verify the plugin was created correctly by reading back the actual plugin.json
  // This guards against any discrepancy between what we intended and what exists on disk.
  const actualPluginJsonPath = join(metaDir, 'plugin.json')
  if (!existsSync(actualPluginJsonPath)) {
    throw new Error(`Plugin creation failed: ${actualPluginJsonPath} does not exist after writing`)
  }
  const actualPluginJson = JSON.parse(await readFile(actualPluginJsonPath, 'utf-8')) as Record<string, string>
  const actualName = actualPluginJson.name
  const actualDescription = actualPluginJson.description || ''
  const actualVersion = actualPluginJson.version || '1.0.0'

  // Verify quad-match: plugin.json name must equal directory name
  const dirName = pluginDir.split('/').pop()
  if (actualName !== dirName) {
    // Fix the mismatch — plugin.json name is the source of truth for the marketplace
    console.warn(`[role-plugin] Quad-match fix: plugin.json name "${actualName}" != dir name "${dirName}". Updating plugin.json.`)
    actualPluginJson.name = dirName!
    await writeFile(actualPluginJsonPath, JSON.stringify(actualPluginJson, null, 2) + '\n')
  }

  // Verify main-agent.md exists
  const mainAgentPath = join(agentsDir, `${mainAgentName}.md`)
  if (!existsSync(mainAgentPath)) {
    throw new Error(`Plugin creation failed: ${mainAgentPath} does not exist after writing`)
  }

  // 5b. Inject AI Maestro compatibility skills (governance rules + agent operations)
  await injectAiMaestroSkills(pluginDir)

  // 6. NOW register in marketplace — only after plugin is fully created and verified
  await ensureMarketplace()
  await updateMarketplaceManifest(
    actualPluginJson.name || pluginName,
    actualDescription,
    actualVersion,
  )

  return { pluginName, pluginDir, mainAgentName }
}

function buildPersonaMarkdown(
  mainAgentName: string,
  agent: TomlAgent,
  config: ParsedToml,
  agentDescription?: string,
): string {
  const { skills, dependencies } = config
  const lines: string[] = []

  const descText = config.description?.text || agent.description || `${agent.name} role agent`

  // Frontmatter — name must match the filename (quad-match rule)
  lines.push('---')
  lines.push(`name: ${mainAgentName}`)
  lines.push(`description: ${descText}`)
  if (agent.model) lines.push(`model: ${agent.model}`)
  lines.push('---')
  lines.push('')

  // Title and description
  lines.push(`# ${agent.name}`)
  lines.push('')
  if (agentDescription) {
    lines.push(agentDescription)
    lines.push('')
  } else if (config.description?.text) {
    lines.push(config.description.text)
    lines.push('')
  } else if (agent.description) {
    lines.push(agent.description)
    lines.push('')
  }

  // Skills section
  const allSkills = [
    ...(skills?.primary || []),
    ...(skills?.secondary || []),
    ...(skills?.specialized || []),
  ]
  if (allSkills.length > 0) {
    lines.push('## Skills')
    lines.push('')
    if (skills?.primary?.length) {
      lines.push('### Primary')
      skills.primary.forEach(s => lines.push(`- ${s}`))
      lines.push('')
    }
    if (skills?.secondary?.length) {
      lines.push('### Secondary')
      skills.secondary.forEach(s => lines.push(`- ${s}`))
      lines.push('')
    }
    if (skills?.specialized?.length) {
      lines.push('### Specialized')
      skills.specialized.forEach(s => lines.push(`- ${s}`))
      lines.push('')
    }
  }

  // Rules
  const rules = config.rules?.recommended || config.rules?.items || []
  if (rules.length > 0) {
    lines.push('## Rules')
    lines.push('')
    rules.forEach(r => lines.push(`- ${r}`))
    lines.push('')
  }

  // Sub-agents
  if (config.agents?.recommended?.length) {
    lines.push('## Agents')
    lines.push('')
    config.agents.recommended.forEach(a => lines.push(`- ${a}`))
    lines.push('')
  }

  // Commands
  if (config.commands?.recommended?.length) {
    lines.push('## Commands')
    lines.push('')
    config.commands.recommended.forEach(c => lines.push(`- /${c}`))
    lines.push('')
  }

  // Hooks
  if (config.hooks?.recommended?.length) {
    lines.push('## Hooks')
    lines.push('')
    config.hooks.recommended.forEach(h => lines.push(`- ${h}`))
    lines.push('')
  }

  // MCP Servers
  if (config.mcp?.recommended?.length) {
    lines.push('## MCP Servers')
    lines.push('')
    config.mcp.recommended.forEach(m => lines.push(`- ${m}`))
    lines.push('')
  }

  // LSP Servers
  if (config.lsp?.recommended?.length) {
    lines.push('## LSP Servers')
    lines.push('')
    config.lsp.recommended.forEach(l => lines.push(`- ${l}`))
    lines.push('')
  }

  // Output Styles
  if (config.output_styles?.recommended?.length) {
    lines.push('## Output Styles')
    lines.push('')
    config.output_styles.recommended.forEach(o => lines.push(`- ${o}`))
    lines.push('')
  }

  // Dependencies (user-scope prerequisites)
  if (dependencies) {
    lines.push('## Dependencies')
    lines.push('')
    const depEntries: [string, string[] | undefined][] = [
      ['Plugins', dependencies.plugins],
      ['Skills', dependencies.skills],
      ['Rules', dependencies.rules],
      ['Agents', dependencies.agents],
      ['Commands', dependencies.commands],
      ['Hooks', dependencies.hooks],
      ['MCP Servers', dependencies.mcp_servers],
      ['LSP Servers', dependencies.lsp_servers],
      ['Output Styles', dependencies.output_styles],
      ['Tools', dependencies.tools],
      ['Frameworks', dependencies.frameworks],
    ]
    for (const [label, items] of depEntries) {
      if (items?.length) {
        lines.push(`- **${label}:** ${items.join(', ')}`)
      }
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ── Marketplace management ─────────────────────────────────

/**
 * Ensure the role-plugins marketplace directory and global registration exist.
 */
export async function ensureMarketplace(): Promise<void> {
  // Create marketplace structure
  await mkdir(MARKETPLACE_META_DIR, { recursive: true })
  await mkdir(PLUGINS_DIR, { recursive: true })

  // Create marketplace.json if it doesn't exist
  if (!existsSync(MARKETPLACE_JSON)) {
    const manifest = {
      name: LOCAL_MARKETPLACE_NAME,
      version: '1.0.0',
      owner: { name: 'local' },
      metadata: {
        description: 'Local role-plugin marketplace managed by AI Maestro',
      },
      plugins: [],
    }
    await writeFile(MARKETPLACE_JSON, JSON.stringify(manifest, null, 2) + '\n')
  }

  // Register in global settings.local.json
  await registerMarketplaceGlobally()
}

async function registerMarketplaceGlobally(): Promise<void> {
  const settings = await loadJsonSafe(USER_GLOBAL_SETTINGS) as Record<string, Record<string, unknown>>
  const ekm = (settings.extraKnownMarketplaces || {}) as Record<string, unknown>

  // The canonical entry with the correct absolute path
  const canonicalEntry = {
    source: {
      source: 'directory',
      path: ROLE_PLUGINS_DIR,
    },
  }

  // Always ensure the canonical entry has the correct absolute path
  // (fixes corrupted or stale paths from earlier versions)
  const existing = ekm[LOCAL_MARKETPLACE_NAME] as Record<string, Record<string, string>> | undefined
  const existingPath = existing?.source?.path
  if (existingPath === ROLE_PLUGINS_DIR) return

  ekm[LOCAL_MARKETPLACE_NAME] = canonicalEntry
  settings.extraKnownMarketplaces = ekm
  await saveJsonSafe(USER_GLOBAL_SETTINGS, settings)
}

export async function updateMarketplaceManifest(
  pluginName: string,
  description: string,
  version: string,
): Promise<void> {
  const manifest = await loadJsonSafe(MARKETPLACE_JSON) as Record<string, unknown>
  const plugins = (manifest.plugins || []) as Array<Record<string, string>>

  // Remove existing entry for this plugin (will re-add)
  const filtered = plugins.filter(p => p.name !== pluginName)
  filtered.push({
    name: pluginName,
    description,
    version,
    source: join(PLUGINS_DIR, pluginName),
  })
  manifest.plugins = filtered

  await writeFile(MARKETPLACE_JSON, JSON.stringify(manifest, null, 2) + '\n')
}

// ── Local installation (re-exported from element-management-service) ──────

export { installPluginLocally, uninstallPluginLocally } from '@/services/element-management-service'

// ── Listing ────────────────────────────────────────────────

/**
 * List all available role plugins, merging two sources:
 * 1. GitHub marketplace manifest — reads marketplace.json to discover available role-plugins
 *    (these are NOT installed yet — they're available for on-demand installation)
 * 2. Local marketplace at ~/agents/role-plugins/ — custom Haephestos-generated plugins
 *
 * Deduplicates by name — marketplace plugins take priority over local ones.
 * NOTE: ai-maestro is NOT a role-plugin despite having the ai-maestro- prefix.
 * Role-plugin identification requires the full quad-match (see CLAUDE.md).
 */
// Governance titles compatible with each predefined role-plugin (from ecosystem-constants)
const PREDEFINED_COMPATIBLE_TITLES = PLUGIN_COMPATIBLE_TITLES

export async function listRolePlugins(): Promise<RolePlugin[]> {
  const pluginsByName = new Map<string, RolePlugin>()

  // Source 1: Predefined role-plugins — always included as the authoritative defaults.
  // These are installed on-demand via `claude install <name>@ai-maestro-plugins --scope local`.
  // PREDEFINED_ROLE_PLUGINS is the source of truth, not the marketplace manifest category field.
  const predefinedDescriptions: Record<string, string> = {
    'ai-maestro-assistant-manager-agent': 'MANAGER — user interlocutor, directs other roles',
    'ai-maestro-chief-of-staff': 'CHIEF-OF-STAFF — per-team agent management, staff planning',
    'ai-maestro-architect-agent': 'ARCHITECT — design documents, requirements, architecture',
    'ai-maestro-orchestrator-agent': 'ORCHESTRATOR — task distribution, kanban, coordination',
    'ai-maestro-integrator-agent': 'INTEGRATOR — quality gates, PR review, merging, releases',
    'ai-maestro-programmer-agent': 'PROGRAMMER — general-purpose implementer, writes code',
    'ai-maestro-maintainer-agent': 'MAINTAINER — single-repo maintenance, issue triage, webhook-driven bugfixes',
  }
  for (const [name, info] of Object.entries(PREDEFINED_ROLE_PLUGINS)) {
    pluginsByName.set(name, {
      name,
      version: '1.0.0',
      description: predefinedDescriptions[name] || '',
      model: undefined,
      program: undefined,
      pluginDir: join(GITHUB_MARKETPLACE_DIR, 'plugins', name),
      source: 'marketplace',
      marketplace: info.marketplace,
      compatibleTitles: PREDEFINED_COMPATIBLE_TITLES[name],
      compatibleClients: ['claude-code'], // All 7 predefined role-plugins are Claude Code exclusive
    })
  }

  // Source 2: Local marketplace — custom Haephestos-generated plugins at ~/agents/role-plugins/
  if (existsSync(PLUGINS_DIR)) {
    const entries = await readdir(PLUGINS_DIR)
    for (const entry of entries) {
      // Skip if already found in marketplace (marketplace takes priority)
      if (pluginsByName.has(entry)) continue

      const pluginDir = join(PLUGINS_DIR, entry)
      const pluginJsonPath = join(pluginDir, '.claude-plugin', 'plugin.json')
      const tomlPath = join(pluginDir, `${entry}.agent.toml`)

      const entryStat = await stat(pluginDir).catch(() => null)
      if (!entryStat?.isDirectory()) continue
      if (!existsSync(pluginJsonPath)) continue

      try {
        const meta = JSON.parse(await readFile(pluginJsonPath, 'utf-8'))
        let model: string | undefined
        let program: string | undefined

        let compatibleTitles: string[] | undefined
        let compatibleClients: string[] | undefined
        if (existsSync(tomlPath)) {
          try {
            const tomlContent = await readFile(tomlPath, 'utf-8')
            const parsed = parseAgentToml(tomlContent)
            model = parsed.agent.model
            program = parsed.agent.program
            compatibleTitles = parsed.agent.compatibleTitles
            compatibleClients = parsed.agent.compatibleClients
          } catch { /* ignore parse errors */ }
        }

        pluginsByName.set(entry, {
          name: meta.name || entry,
          version: meta.version || '1.0.0',
          description: meta.description || '',
          model,
          program,
          pluginDir,
          source: 'local',
          marketplace: LOCAL_MARKETPLACE_NAME,
          compatibleTitles,
          compatibleClients,
        })
      } catch { /* skip malformed plugins */ }
    }
  }

  return Array.from(pluginsByName.values())
}

/**
 * Return role-plugins filtered by compatible-titles and optionally compatible-clients.
 * Both comparisons are case-insensitive.
 *
 * Client name normalization: callers may pass the short form (`claude`, `codex`)
 * OR the canonical form used in TOML files (`claude-code`, `codex`). We normalize
 * the short forms to the canonical TOML form before comparing, so the wizard
 * (which uses short form `claude`) matches predefined plugins (which declare
 * `compatible-clients = ["claude-code"]`). Without this normalization the filter
 * silently excludes ALL predefined plugins for any team title.
 */
export async function getPluginsForTitle(title: string, clientType?: string): Promise<RolePlugin[]> {
  const all = await listRolePlugins()
  const upperTitle = title.toUpperCase()
  // Normalize short → canonical form used in .agent.toml compatible-clients.
  const CLIENT_ALIAS_MAP: Record<string, string> = {
    'claude': 'claude-code',
    'claude-code': 'claude-code',
    'codex': 'codex',
    'gemini': 'gemini',
    'opencode': 'opencode',
    'kiro': 'kiro',
  }
  const rawClient = clientType?.toLowerCase()
  const canonicalClient = rawClient ? (CLIENT_ALIAS_MAP[rawClient] ?? rawClient) : undefined
  return all.filter(p => {
    // Must match compatible-titles
    if (!p.compatibleTitles?.includes(upperTitle)) return false
    // If client filter specified, must also match compatible-clients (or have none = any client)
    if (canonicalClient && p.compatibleClients && p.compatibleClients.length > 0) {
      if (!p.compatibleClients.includes(canonicalClient)) return false
    }
    return true
  })
}

/**
 * Delete a role plugin from the local marketplace.
 * Cannot delete default marketplace role plugins — those are managed by `claude plugin`.
 */
export async function deleteRolePlugin(pluginName: string): Promise<void> {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(pluginName)) {
    throw new Error(`Invalid plugin name "${pluginName}"`)
  }

  // Guard: default marketplace plugins cannot be deleted via this API
  if (DEFAULT_ROLE_PLUGIN_NAMES.includes(pluginName)) {
    throw new Error(`Cannot delete default marketplace role plugins. Use "claude plugin uninstall ${pluginName}" instead.`)
  }

  const pluginDir = join(PLUGINS_DIR, pluginName)
  if (existsSync(pluginDir)) {
    await rm(pluginDir, { recursive: true })
  }

  // Remove from marketplace manifest
  if (existsSync(MARKETPLACE_JSON)) {
    const manifest = await loadJsonSafe(MARKETPLACE_JSON) as Record<string, unknown>
    const plugins = (manifest.plugins || []) as Array<Record<string, string>>
    manifest.plugins = plugins.filter(p => p.name !== pluginName)
    await writeFile(MARKETPLACE_JSON, JSON.stringify(manifest, null, 2) + '\n')
  }

  // Remove from global enabledPlugins
  const pluginKey = `${pluginName}@${LOCAL_MARKETPLACE_NAME}`
  if (existsSync(USER_GLOBAL_SETTINGS)) {
    const settings = await loadJsonSafe(USER_GLOBAL_SETTINGS) as Record<string, Record<string, unknown>>
    const ep = (settings.enabledPlugins || {}) as Record<string, boolean>
    delete ep[pluginKey]
    settings.enabledPlugins = ep
    await saveJsonSafe(USER_GLOBAL_SETTINGS, settings)
  }
}

// ── Unified persona creation ─────────────────────────────

/**
 * The 7 predefined AI Maestro role plugins.
 * Built from ecosystem-constants (ROLE_PLUGIN_MAIN_AGENTS + GITHUB_MARKETPLACE_NAME).
 * These are available in the marketplace but are NOT auto-installed.
 * They are installed ON-DEMAND when a user selects one from the dropdown via installPluginLocally().
 */
export const PREDEFINED_ROLE_PLUGINS: Record<string, { marketplace: string; mainAgent: string }> =
  Object.fromEntries(
    PREDEFINED_ROLE_PLUGIN_NAMES.map(name => [
      name,
      { marketplace: GITHUB_MARKETPLACE_NAME, mainAgent: ROLE_PLUGIN_MAIN_AGENTS[name] },
    ])
  )

// ── Default role plugin sync ──────────────────────────────

export interface SyncDefaultsResult {
  synced: string[]
  skipped: string[]
  errors: Array<{ name: string; error: string }>
  available: string[]
}

/**
 * Ensure the Emasoft/ai-maestro-plugins marketplace is registered and return
 * the list of available role-plugins from the marketplace metadata.
 *
 * IMPORTANT: This does NOT install any role-plugins. Role-plugins are installed
 * ON-DEMAND when a user selects one from the dropdown. This function only:
 * 1. Ensures the marketplace Emasoft/ai-maestro-plugins is registered
 * 2. Returns the list of available role-plugins from the marketplace manifest
 * 3. Migrates existing agent settings from old marketplace keys
 *
 * @param _force - Kept for API compatibility (ignored — nothing to force-install)
 */
export async function syncDefaultRolePlugins(_force = false): Promise<SyncDefaultsResult> {
  const synced: string[] = []
  const skipped: string[] = []
  const errors: Array<{ name: string; error: string }> = []
  const available: string[] = []

  // Step 1: Ensure the GitHub marketplace is registered (does not install any plugins)
  try {
    await execFileAsync('claude', ['plugin', 'marketplace', 'add', MARKETPLACE_REPO], { timeout: 60000 })
    synced.push('marketplace-registered')
    console.log(`[role-plugins] GitHub marketplace ${MARKETPLACE_REPO} registered`)
  } catch (err) {
    // Marketplace may already be registered — not a fatal error
    const msg = err instanceof Error ? err.message : String(err)
    if (msg.includes('already') || msg.includes('exists')) {
      skipped.push('marketplace-already-registered')
    } else {
      errors.push({ name: 'marketplace-registration', error: msg })
    }
    console.warn('[role-plugins] Marketplace add note:', msg)
  }

  // Step 2: Read the marketplace manifest, fix source format if needed, discover role-plugins.
  // Claude CLI requires source format: { "source": "url", "url": "<git_url>" }
  // but the upstream repo may use { "type": "git", "repo": "<git_url>" } which doesn't work.
  if (existsSync(GITHUB_MARKETPLACE_MANIFEST)) {
    try {
      const manifest = JSON.parse(await readFile(GITHUB_MARKETPLACE_MANIFEST, 'utf-8')) as {
        plugins?: Array<{ name: string; category?: string; source?: unknown }>
      }
      const plugins = manifest.plugins || []
      let manifestFixed = false
      for (const entry of plugins) {
        // Fix source format: { type: "git", repo: "..." } → { source: "url", url: "..." }
        const src = entry.source as Record<string, string> | string | undefined
        if (src && typeof src === 'object' && (src as Record<string, string>).type === 'git' && (src as Record<string, string>).repo) {
          ;(entry as Record<string, unknown>).source = { source: 'url', url: (src as Record<string, string>).repo }
          manifestFixed = true
        }
        // Collect available role-plugins
        if (entry.category === 'role-plugin') {
          available.push(entry.name)
        }
      }
      // Write back the fixed manifest so `claude plugin install` works
      if (manifestFixed) {
        await writeFile(GITHUB_MARKETPLACE_MANIFEST, JSON.stringify(manifest, null, 4) + '\n')
        console.log('[role-plugins] Fixed marketplace manifest source format for Claude CLI compatibility')
      }
    } catch {
      console.warn('[role-plugins] Could not read marketplace manifest for available plugins')
    }
  }

  // Also include the known predefined names (in case manifest hasn't been updated yet)
  for (const name of DEFAULT_ROLE_PLUGIN_NAMES) {
    if (!available.includes(name)) {
      available.push(name)
    }
  }

  // Step 3: Migrate existing agent settings from old local marketplace key to GitHub marketplace key
  await migrateDefaultPluginSettings()

  return { synced, skipped, errors, available }
}

/**
 * Migrate agent settings: change old marketplace keys to current @ai-maestro-plugins.
 * Also removes the deprecated 23blocks-OS marketplace from Claude CLI.
 */
async function migrateDefaultPluginSettings(): Promise<void> {
  // Step 1: Remove deprecated 23blocks-OS marketplace (replaced by Emasoft/ai-maestro-plugins)
  try {
    const { execSync } = await import('child_process')
    // Try both short and full URL forms — CLI may accept either
    execSync('claude plugin marketplace remove 23blocks-OS/ai-maestro-plugins', { timeout: 10000, stdio: 'pipe' }).toString()
    console.log('[role-plugins] Removed deprecated 23blocks-OS marketplace')
  } catch {
    try {
      const { execSync } = await import('child_process')
      execSync('claude plugin marketplace remove https://github.com/23blocks-OS/ai-maestro-plugins', { timeout: 10000, stdio: 'pipe' }).toString()
      console.log('[role-plugins] Removed deprecated 23blocks-OS marketplace (full URL)')
    } catch {
      // Not registered or already removed — fine
    }
  }

  // Step 1b: Remove deprecated local marketplace names from global settings
  try {
    const settings = await loadJsonSafe(USER_GLOBAL_SETTINGS) as Record<string, Record<string, unknown>>
    const ekm = (settings.extraKnownMarketplaces || {}) as Record<string, unknown>
    const deprecatedNames = ['ai-maestro-local-agents-marketplace', 'ai-maestro-local-marketplace', 'role-plugins']
    let cleaned = false
    for (const name of deprecatedNames) {
      if (ekm[name]) { delete ekm[name]; cleaned = true }
    }
    if (cleaned) {
      settings.extraKnownMarketplaces = ekm
      await saveJsonSafe(USER_GLOBAL_SETTINGS, settings)
      console.log('[role-plugins] Cleaned deprecated marketplace names from global settings')
    }
  } catch { /* ignore */ }

  // Step 2: Migrate agent settings from old local marketplace key to GitHub marketplace key
  const agentsBaseDir = join(HOME, 'agents')
  if (!existsSync(agentsBaseDir)) return

  try {
    const entries = await readdir(agentsBaseDir)
    for (const entry of entries) {
      const settingsPath = join(agentsBaseDir, entry, '.claude', 'settings.local.json')
      if (!existsSync(settingsPath)) continue

      try {
        const settings = await loadJsonSafe(settingsPath) as Record<string, Record<string, unknown>>
        const ep = (settings.enabledPlugins || {}) as Record<string, boolean>
        let changed = false

        for (const pluginName of DEFAULT_ROLE_PLUGIN_NAMES) {
          // Migrate from local marketplace key → GitHub marketplace key
          const oldLocalKey = `${pluginName}@${LOCAL_MARKETPLACE_NAME}`
          const newKey = `${pluginName}@${GITHUB_MARKETPLACE_NAME}`
          if (ep[oldLocalKey] !== undefined && ep[newKey] === undefined) {
            ep[newKey] = ep[oldLocalKey]
            delete ep[oldLocalKey]
            changed = true
          }
          // Also migrate from old deprecated names (ai-maestro-local-agents-marketplace, etc.)
          const legacyKeys = [
            `${pluginName}@ai-maestro-local-agents-marketplace`,
            `${pluginName}@ai-maestro-local-marketplace`,
            `${pluginName}@role-plugins`,
          ]
          for (const legacyKey of legacyKeys) {
            if (ep[legacyKey] !== undefined && ep[newKey] === undefined) {
              ep[newKey] = ep[legacyKey]
              delete ep[legacyKey]
              changed = true
            } else if (ep[legacyKey] !== undefined) {
              delete ep[legacyKey]  // Duplicate — just remove
              changed = true
            }
          }
        }

        if (changed) {
          settings.enabledPlugins = ep
          await saveJsonSafe(settingsPath, settings)
          console.log(`[role-plugins] Migrated settings for agent: ${entry}`)
        }
      } catch { /* skip individual agent errors */ }
    }
  } catch { /* skip if agents dir can't be read */ }
}

// ── Governance title → role-plugin mapping (re-exported from element-management-service) ───

export {
  getRequiredPluginForTitle,
  autoAssignRolePluginForTitle,
  uninstallAllRolePlugins,
  syncRolePlugin as syncRolePluginForTitle,
  syncRolePlugin,
} from '@/services/element-management-service'

export interface CreatePersonaResult {
  personaName: string
  agentDir: string
  pluginName: string
  mainAgentName: string
  marketplaceName: string
}

/**
 * Unified persona creation — used by both the wizard (predefined role plugins)
 * and Haephestos (custom TOML-generated plugins).
 *
 * Exactly one of `tomlContent` or `pluginName` must be provided:
 * - tomlContent: Haephestos flow — generates a new plugin, adds to local marketplace
 * - pluginName: Wizard flow — uses an existing predefined role plugin
 *
 * In both cases, creates ~/agents/<personaName>/ and installs the plugin
 * with --scope local into that folder.
 */
export async function createPersona(opts: {
  personaName: string
  tomlContent?: string
  pluginName?: string
  marketplaceName?: string
  agentDescription?: string
}): Promise<CreatePersonaResult> {
  const { personaName, tomlContent, agentDescription } = opts

  // Validate persona name: lowercase alphanumeric + hyphens
  if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(personaName)) {
    throw new Error('personaName must be lowercase alphanumeric with hyphens (e.g. "peter-bot")')
  }

  // Must provide exactly one source
  if (tomlContent && opts.pluginName) {
    throw new Error('Provide either tomlContent or pluginName, not both')
  }
  if (!tomlContent && !opts.pluginName) {
    throw new Error('Either tomlContent or pluginName is required')
  }

  let pluginName: string
  let mainAgentName: string
  let marketplaceName: string

  if (tomlContent) {
    // Haephestos flow: generate plugin from TOML → local marketplace
    // Note: Haephestos is responsible for adding compatible-titles/clients to the TOML
    // before calling this API. The API saves the TOML as-is.
    const result = await generatePluginFromToml(tomlContent, agentDescription)
    pluginName = result.pluginName
    mainAgentName = result.mainAgentName
    marketplaceName = LOCAL_MARKETPLACE_NAME
  } else {
    // Wizard flow: use existing predefined plugin
    pluginName = opts.pluginName!
    const predefined = PREDEFINED_ROLE_PLUGINS[pluginName]
    if (predefined) {
      marketplaceName = opts.marketplaceName || predefined.marketplace
      mainAgentName = predefined.mainAgent
    } else {
      // Custom plugin name — caller must specify marketplace
      marketplaceName = opts.marketplaceName || LOCAL_MARKETPLACE_NAME
      mainAgentName = `${pluginName}-main-agent`
    }
  }

  // Create the persona folder: ~/agents/<personaName>/
  const agentDir = join(HOME, 'agents', personaName)
  await mkdir(agentDir, { recursive: true })

  // Install the plugin locally into the persona folder
  await _installPluginLocally(pluginName, agentDir, marketplaceName)

  return {
    personaName,
    agentDir,
    pluginName,
    mainAgentName,
    marketplaceName,
  }
}
