#!/usr/bin/env bash
# Per-scenario cleanup wrapper — delegates to shared scenario-restore.sh, THEN
# scrubs the per-run artifacts that folder ADOPTION seeded into the permanent
# dir fixture (SCEN-028 adopts ~/agents/scen028-import-fixture IN PLACE, so the
# seeded .claude/ files + the managed .git/info/exclude block are per-run
# artifacts inside a fixture that must stay pristine across runs — `git reset
# --hard scenario-start` cannot remove them because they are untracked/outside
# the work tree).
set -u
"$(dirname "$0")/scenario-restore.sh" 028 "$@" || exit $?

FIXTURE="$HOME/agents/scen028-import-fixture"
[ -d "$FIXTURE" ] || { echo "cleanup-SCEN-028: fixture missing at $FIXTURE" >&2; exit 0; }

# Seeded DEP rules + local plugin config (untracked — safe to remove: they are
# regenerated by the adoption pipeline on every run).
rm -f "$FIXTURE"/.claude/rules/aimaestro-*.md
rm -f "$FIXTURE/.claude/settings.local.json"
rmdir "$FIXTURE/.claude/rules" 2>/dev/null || true
rmdir "$FIXTURE/.claude" 2>/dev/null || true

# Managed block in .git/info/exclude (between the ai-maestro markers).
EXCLUDE="$FIXTURE/.git/info/exclude"
if [ -f "$EXCLUDE" ] && grep -q 'ai-maestro:managed-gitignore' "$EXCLUDE"; then
  TMP="$(mktemp)"
  awk '/# >>> ai-maestro:managed-gitignore/{skip=1} skip==0{print} /# <<< ai-maestro:managed-gitignore/{skip=0}' \
    "$EXCLUDE" > "$TMP" && mv "$TMP" "$EXCLUDE"
  echo "cleanup-SCEN-028: managed exclude block scrubbed"
fi

echo "cleanup-SCEN-028: fixture pristine"
