/**
 * Agent shell-guard — installs a `cd` override into the agent's tmux
 * pane shell so the agent (and anyone who happens to acquire the bare
 * shell prompt during a transition) cannot leave the agent's working
 * directory or `/tmp`.
 *
 * This is a defence-in-depth layer, NOT a sandbox. A determined
 * attacker with shell access can bypass any function override
 * (`\cd`, `command cd`, `bash -c 'cd /etc'`, subshells, etc.). The
 * value is:
 *   - bystander click + stray keystroke can't leave the agent dir,
 *   - automated tooling driving the dashboard can't accidentally
 *     `cd` into the source repo and damage it,
 *   - clear telemetry + user-visible refusal message.
 *
 * The OS-level boundary is, and has always been, that AI Maestro runs
 * the agent in the user's UID — so anything `bash -c 'rm -rf $HOME'`
 * could do is already inside the trust boundary. The cd-override
 * exists to make accidental damage hard, not to defeat hostile shell
 * users.
 *
 * Sourcing strategy:
 *   1. AI Maestro writes this script to `~/.aimaestro/agent-shell-guard.sh`
 *      atomically (tmp+rename) on first wake of the process, and on every
 *      version change (the version line below is part of the file).
 *   2. The wake path sends one `source ~/.aimaestro/agent-shell-guard.sh`
 *      into the tmux pane BEFORE launching `claude` (or whichever AI
 *      client). The override lives in the shell process — so when the
 *      AI program exits and the shell prompt comes back, the override
 *      is still active.
 *   3. The override reads `$AGENT_WORK_DIR` (set by tmux at session
 *      creation via `-e AGENT_WORK_DIR=...`) for the allow-list anchor.
 *      If that var is unset for any reason, the guard fails OPEN
 *      (does NOT block) — the lack of the variable means we are not
 *      in an AI Maestro-managed shell and the caller likely intended
 *      to use cd normally.
 */

export const SHELL_GUARD_VERSION = '1.0.0' as const

export const SHELL_GUARD_SCRIPT = `#!/usr/bin/env bash
# AI Maestro agent shell guard — version ${SHELL_GUARD_VERSION}
#
# Auto-generated by AI Maestro. Do not edit by hand — re-running
# AI Maestro will overwrite the file with the canonical version.
#
# Confines \`cd\` and \`pushd\` to:
#   - $AGENT_WORK_DIR/**       (the agent's own project directory)
#   - /tmp/**, /private/tmp/** (POSIX scratch + macOS-mapped scratch)
#   - /var/folders/**          (macOS user-scoped temp)
#
# When AGENT_WORK_DIR is unset (i.e. the shell isn't part of an AI
# Maestro-managed agent session), the guard is a no-op.

if [ -z "\${AGENT_WORK_DIR:-}" ]; then
  return 0 2>/dev/null || exit 0
fi

# Cache the resolved AGENT_WORK_DIR so the allow-list comparison is O(1)
# and consistent with macOS's /tmp -> /private/tmp symlink resolution.
__aim_workdir_resolved=$(
  builtin cd "\${AGENT_WORK_DIR}" 2>/dev/null && builtin pwd -P
)
if [ -z "\$__aim_workdir_resolved" ]; then
  # AGENT_WORK_DIR points at a path that doesn't exist — abort guard
  # install rather than refuse every cd.
  return 0 2>/dev/null || exit 0
fi

__aim_path_allowed() {
  local target="\${1:-}"
  if [ -z "\$target" ]; then target="\$HOME"; fi

  # Resolve to absolute physical path via a subshell builtin cd so the
  # parent shell's PWD is never mutated.
  local resolved
  resolved=\$(builtin cd "\$target" 2>/dev/null && builtin pwd -P)
  if [ -z "\$resolved" ]; then
    # cd would fail anyway — let the real cd surface the error.
    return 0
  fi

  case "\$resolved" in
    "\$__aim_workdir_resolved"|"\$__aim_workdir_resolved"/*) return 0 ;;
    /tmp|/tmp/*|/private/tmp|/private/tmp/*) return 0 ;;
    /var/folders|/var/folders/*) return 0 ;;
  esac

  printf '[aimaestro] cd refused: %s is outside the agent directory (%s) and /tmp.\\n' \\
    "\$resolved" "\$__aim_workdir_resolved" >&2
  printf '[aimaestro] To override per-shell: type \\\`unset -f cd pushd\\\` (this leaves the guard for new shells).\\n' >&2
  return 1
}

cd() {
  if __aim_path_allowed "\${1:-}"; then
    builtin cd "\$@"
  else
    return 1
  fi
}

pushd() {
  # First arg of pushd is the destination (or +N/-N for stack rotation,
  # which doesn't change cwd to a new path — those are safe).
  local first="\${1:-}"
  case "\$first" in
    +[0-9]*|-[0-9]*|'') builtin pushd "\$@"; return ;;
  esac
  if __aim_path_allowed "\$first"; then
    builtin pushd "\$@"
  else
    return 1
  fi
}

# popd is safe — it can only return to a path already on the dir stack,
# all of which were vetted by the override above when they were pushed.

# Mark guard as installed so the wake path can sanity-check via
# \`type cd\` if needed. (Functions show as "function" in \`type\`.)
__AIM_SHELL_GUARD_LOADED=1
export __AIM_SHELL_GUARD_LOADED
`
