#!/usr/bin/env bash
# Put the TRDD/PRRD QUERY surface on PATH for every project on this host (ai-maestro#104).
#
# WHY THIS EXISTS. The janitor installs three IND governance rules to `~/.claude/rules/` in EVERY
# session on the machine, ai-maestro or not, and those rules instruct agents to resolve a card with
# a tool that was reachable only from this repo. An agent that follows the rule got
# `command not found`; an agent that did not hand-grepped the corpus and reached a DIFFERENT answer
# than the tool would. Both outcomes are worse than the rule not existing, and the second is what
# produced the `grep '^status:' -> 0` mistake that cost three round-trips: three agents invented
# three anchors because none of them had the shared instrument. `memgrep` already has this property
# — it lives on PATH and is invoked identically from an agent workdir and a plain repo — which is
# why the memory half of the 3-pillars system works everywhere and the TRDD half did not.
#
# WHY A WRAPPER AND NOT A SYMLINK. `trddgrep.mjs` is `#!/usr/bin/env node`, but it loads this repo's
# TypeScript `lib/` through `tsx` and reaches a SQLite index, so it needs both the repo and the
# pinned Node 22 (`node-pty`/`better-sqlite3` cap the ABI — an unsupported Node does not degrade it,
# it fails). A bare symlink resolves the binary and then dies on the first import.
#
# THE ONE PROPERTY THAT MAKES IT USEFUL ELSEWHERE: `trddgrep.mjs:113` resolves the corpus as
# `path.join(process.cwd(), 'design')`, and `with-node.sh` does NOT change directory (it execs in
# place). So the wrapper runs the CALLER's corpus, not ai-maestro's. If either of those ever
# changes, this whole script becomes a tool that silently reports ai-maestro's board to every
# project on the host — which is worse than not shipping it, so both are asserted in the test.
#
# READ EVERYWHERE, REPAIR ONLY HERE. The janitor asked for exactly this split and it is right: a
# plain repo with no MANAGER and no approval chain should not get a mutating fixer by default, and
# `fix` is the verb that rewrites frontmatter across a whole corpus. The wrapper therefore refuses
# the mutating verbs when the caller's corpus is not inside this checkout.
#
# It is a DEFAULT, not a security boundary, and the difference is stated so nobody mistakes it for
# one: anyone can still run the `.mjs` directly, and `AIM_PILLAR_ALLOW_WRITE=1` lifts it on purpose.
# The hazard being prevented is an accidental corpus-wide rewrite in a project that never opted in,
# not an attacker — and a guard sold as stronger than it is gets trusted where it should not be.

set -euo pipefail

AIM_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_BIN="${AIM_PILLAR_BIN_DIR:-$HOME/.local/bin}"

# The canonical names. `<doctype>grep` matches `memgrep`, which shipped first and set the
# convention — ai-maestro#104 asks which of four spellings in play is canonical, and this file is
# the answer. A name that cannot be GUESSED from the corpus it reads is not really installed.
PILLAR_CLIS="trddgrep prrdgrep"

mkdir -p "$LOCAL_BIN"

emit_wrapper() {
    local cli="$1" dest="$LOCAL_BIN/$1"
    # The root is BAKED at install time rather than discovered at run time: the wrapper runs from an
    # arbitrary cwd, so there is nothing to discover it from, and a wrapper that guessed would find
    # whichever repo the caller happened to be standing in.
    cat > "$dest" <<WRAPPER
#!/usr/bin/env bash
# GENERATED by ai-maestro scripts/install-pillar-tooling.sh — do not edit, re-run the installer.
set -euo pipefail
AIM_ROOT='$AIM_ROOT'

# First non-flag argument is the verb.
verb=''
for a in "\$@"; do
    case "\$a" in -*) ;; *) verb="\$a"; break ;; esac
done

# Is the caller's corpus inside the ai-maestro checkout? Trailing slash on both sides so the root
# itself matches (a shell \`*\` matches the empty string).
inside=0
case "\$PWD/" in "\$AIM_ROOT"/*) inside=1 ;; esac

case "\$verb" in
    fix|edit)
        if [ "\$inside" -eq 0 ] && [ "\${AIM_PILLAR_ALLOW_WRITE:-}" != "1" ]; then
            echo "$cli: '\$verb' rewrites the corpus and is disabled outside the ai-maestro checkout." >&2
            echo "  The query surface (board, next, why, show, lint, validate, env) works here." >&2
            echo "  Deliberate? AIM_PILLAR_ALLOW_WRITE=1 $cli \$verb ..." >&2
            exit 2   # 2 = COULD NOT RUN, never 1 — 1 means 'found findings' for these CLIs.
        fi
        ;;
esac

# \`--import tsx\` resolves the BARE specifier against the CWD, not against the script, so from any
# other project it dies with ERR_MODULE_NOT_FOUND before the CLI runs. Only running the wrapper
# from a scratch project shows that; from inside this repo it works and proves nothing.
# So: an absolute file: URL, which is cwd-independent — and cwd stays the CALLER's, because that is
# how the CLI finds their corpus.
# It must be the package's MAIN entry (\`dist/loader.mjs\`), NOT \`dist/esm/index.mjs\`: the esm entry
# registers only half the hooks, and the CLI then dies on ERR_REQUIRE_CYCLE_MODULE inside
# lib/trdd-store.ts. Two different absolute paths, one works — which is why this is asserted.
# And the \`@/*\` path alias is resolved from the CWD's tsconfig, which another project does not
# have — so tsx is pointed at OURS explicitly. Without it the CLI dies on \`Cannot find module
# '@/types/task'\`. Three separate cwd assumptions, all invisible from inside this repo.
TSX_TSCONFIG_PATH="\$AIM_ROOT/tsconfig.json" \\
exec bash "\$AIM_ROOT/scripts/with-node.sh" node --import "file://\$AIM_ROOT/node_modules/tsx/dist/loader.mjs" "\$AIM_ROOT/scripts/$cli.mjs" "\$@"
WRAPPER
    chmod +x "$dest"
}

installed=0
for cli in $PILLAR_CLIS; do
    if [ ! -f "$AIM_ROOT/scripts/$cli.mjs" ]; then
        echo "  $cli — SKIPPED (scripts/$cli.mjs not found)" >&2
        continue
    fi
    emit_wrapper "$cli"
    echo "  $cli — installed -> $LOCAL_BIN/$cli"
    installed=$((installed + 1))
done

case ":$PATH:" in
    *":$LOCAL_BIN:"*) ;;
    *) echo "  NOTE: $LOCAL_BIN is not on PATH — add it to your shell rc." >&2 ;;
esac

echo "  $installed pillar CLI(s) on PATH. Query surface is machine-wide; 'fix'/'edit' stay inside $AIM_ROOT."
