#!/usr/bin/env node
// Generates a topic-grouped index of the project wikimem pages (.claude/project/memory/).
// Each page's frontmatter carries metadata.topic; this script groups by topic and
// emits one bullet per page. See metadata schema in the pages themselves.
//
// Usage:
//   node scripts/wikimem-index.mjs [--dir <path>] [--check] [--write <file> ...]
//
//   --dir <path>    memory directory to scan (default: .claude/project/memory)
//   --check         exit 1 if any page lacks metadata.topic (prints offending names);
//                    exit 0 and print nothing otherwise. No index is printed in this mode.
//   --write <file>  splice the index between the WIKIMEM-INDEX fences in <file>
//                    (repeatable). Fails loudly if the fences are absent.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

// Canonical topic order — matches the assignment used to tag the corpus.
const TOPIC_ORDER = [
  'architecture-and-runtime',
  'agents',
  'teams-and-governance',
  'messaging',
  'plugins-and-marketplaces',
  'security-and-auth',
  'design-system',
  'reliability-patterns',
  'tooling-and-testing',
  'overview',
]

const TOPIC_TITLES = {
  'architecture-and-runtime': 'Architecture and Runtime',
  'agents': 'Agents',
  'teams-and-governance': 'Teams and Governance',
  'messaging': 'Messaging',
  'plugins-and-marketplaces': 'Plugins and Marketplaces',
  'security-and-auth': 'Security and Auth',
  'design-system': 'Design System',
  'reliability-patterns': 'Reliability Patterns',
  'tooling-and-testing': 'Tooling and Testing',
  'overview': 'Overview',
}

// The fences --write splices between. Both destinations (CLAUDE.md and the wiki's
// own overview hub) need the SAME list, and a list maintained by hand in two places
// is two lists that will disagree — which is the exact failure this whole index
// exists to stop. So the generator writes both, and hand-editing between the fences
// is pointless: the next run overwrites it.
const FENCE_START = '<!-- WIKIMEM-INDEX-START (generated by scripts/wikimem-index.mjs — do not edit between the fences) -->'
const FENCE_END = '<!-- WIKIMEM-INDEX-END -->'

function parseArgs(argv) {
  let dir = '.claude/project/memory'
  let check = false
  const writes = []
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--dir') {
      dir = argv[++i]
    } else if (argv[i] === '--check') {
      check = true
    } else if (argv[i] === '--write') {
      writes.push(argv[++i])
    }
  }
  return { dir, check, writes }
}

// Splice the block between the fences. FAILS LOUDLY when a fence is missing rather
// than appending — a silent append would leave two copies of the index in one file,
// and the second would look as authoritative as the first.
function spliceInto(file, block) {
  const text = readFileSync(file, 'utf8')
  const a = text.indexOf(FENCE_START)
  const b = text.indexOf(FENCE_END)
  if (a === -1 || b === -1 || b < a) {
    throw new Error(
      `${file}: missing or malformed WIKIMEM-INDEX fences. Add these two lines where the ` +
      `index belongs:\n${FENCE_START}\n${FENCE_END}`,
    )
  }
  const next = text.slice(0, a) + FENCE_START + '\n\n' + block.trimEnd() + '\n\n' + text.slice(b)
  if (next === text) return false
  writeFileSync(file, next)
  return true
}

// Extracts the leading YAML frontmatter block (--- ... ---) as raw text.
// Returns null when the file has no frontmatter (e.g. MEMORY.md), which is how
// non-wiki files are skipped — by structure, never by a hardcoded filename list.
function extractFrontmatter(text) {
  if (!text.startsWith('---\n') && !text.startsWith('---\r\n')) return null
  const end = text.indexOf('\n---', 4)
  if (end === -1) return null
  return text.slice(0, end)
}

// Minimal line-based reader for the three fields we need — avoids a YAML dependency.
function readField(frontmatter, key) {
  const re = new RegExp(`^${key}:\\s*(.*)$`, 'm')
  const m = frontmatter.match(re)
  if (!m) return null
  let value = m[1].trim()
  // Strip a single layer of surrounding quotes, if present.
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    value = value.slice(1, -1)
  }
  return value || null
}

function readTopic(frontmatter) {
  // metadata.topic is indented two spaces under the `metadata:` block.
  const m = frontmatter.match(/^ {2}topic:\s*(.*)$/m)
  if (!m) return null
  return m[1].trim() || null
}

// A `description:` is a slash-separated SYMPTOM list written for search, not for
// reading. Turning it into an index line needs both guards, because the two failure
// modes are opposite and both were observed on the first generated pass:
//
//   too SHORT — `/` is also used INSIDE a phrase ("the janitor / a governance agent",
//     "what is tldr / fastedit"), so a naive first-clause cut yields "how does the
//     janitor" or "what is tldr" — a fragment that identifies nothing.
//   too LONG — some descriptions open with a full paragraph, which turns one bullet
//     into four lines and makes the index unscannable, which is its only job.
//
// So: keep appending clauses until the line carries enough to identify the page, then
// hard-cap it. Both bounds are deliberate; neither alone is sufficient.
const MIN_CLAUSE_CHARS = 30
const MAX_LINE_CHARS = 110

function firstClause(description) {
  if (!description) return ''
  const clauses = description.split('/').map((c) => c.trim()).filter(Boolean)
  let line = ''
  for (const clause of clauses) {
    line = line ? `${line} / ${clause}` : clause
    if (line.length >= MIN_CLAUSE_CHARS) break
  }
  if (line.length > MAX_LINE_CHARS) line = line.slice(0, MAX_LINE_CHARS).replace(/\s+\S*$/, '') + '…'
  return line
}

function loadPages(dir) {
  const pages = []
  for (const entry of readdirSync(dir)) {
    if (!entry.endsWith('.md')) continue
    const path = join(dir, entry)
    const text = readFileSync(path, 'utf8')
    const frontmatter = extractFrontmatter(text)
    if (frontmatter === null) continue // no frontmatter -> not a wiki page, skip

    const name = readField(frontmatter, 'name') || entry.replace(/\.md$/, '')
    const description = readField(frontmatter, 'description')
    const topic = readTopic(frontmatter)
    pages.push({ name, description, topic })
  }
  return pages
}

function main() {
  const { dir, check, writes } = parseArgs(process.argv.slice(2))
  const pages = loadPages(dir)

  if (check) {
    const missing = pages.filter((p) => !p.topic).map((p) => p.name).sort()
    // TOPIC_ORDER is a CLOSED vocabulary, so an off-vocabulary value is always a typo — and it
    // fails INVISIBLY. An unknown topic is appended as its own group and rendered raw
    // (`TOPIC_TITLES[topic] || topic`), so `topic: Agents` produced a SECOND `### Agents` heading
    // byte-identical to the real one in the rendered index. Nothing downstream complains: the page
    // is present, its row is there, and the only symptom is a duplicate section a reader assumes is
    // intentional. Checking PRESENCE alone could never catch it.
    const unknown = pages
      .filter((p) => p.topic && !TOPIC_ORDER.includes(p.topic))
      .map((p) => `${p.name} (topic: ${p.topic})`)
      .sort()

    // Both classes are reported in ONE run, and neither exits early. An early exit on `missing`
    // would mask every `unknown` behind whichever page happened to lack a topic that day — so the
    // second check would sit there looking enforced while being unreachable.
    if (missing.length > 0) {
      console.error(`wikimem-index --check: ${missing.length} page(s) missing metadata.topic:`)
      for (const name of missing) console.error(`  - ${name}`)
    }
    if (unknown.length > 0) {
      console.error(`wikimem-index --check: ${unknown.length} page(s) with an unknown metadata.topic:`)
      for (const row of unknown) console.error(`  - ${row}`)
      console.error(`  known topics: ${TOPIC_ORDER.join(', ')}`)
    }
    process.exit(missing.length + unknown.length > 0 ? 1 : 0)
  }

  const byTopic = new Map()
  for (const page of pages) {
    if (!page.topic) continue
    // The overview IS the front door and the index sits on it, so listing it would be
    // circular. Prose names the entry point; the index lists what it points AT.
    if (page.topic === 'overview') continue
    if (!byTopic.has(page.topic)) byTopic.set(page.topic, [])
    byTopic.get(page.topic).push(page)
  }

  const orderedTopics = [
    ...TOPIC_ORDER.filter((t) => byTopic.has(t)),
    ...[...byTopic.keys()].filter((t) => !TOPIC_ORDER.includes(t)).sort(),
  ]

  const lines = []
  for (const topic of orderedTopics) {
    const title = TOPIC_TITLES[topic] || topic
    lines.push(`### ${title}`)
    lines.push('')
    const pagesInTopic = [...byTopic.get(topic)].sort((a, b) => a.name.localeCompare(b.name))
    for (const page of pagesInTopic) {
      lines.push(`- **\`${page.name}\`** — ${firstClause(page.description)}`)
    }
    lines.push('')
  }

  const block = lines.join('\n').trimEnd() + '\n'

  if (writes.length > 0) {
    for (const file of writes) {
      const changed = spliceInto(file, block)
      console.error(`wikimem-index: ${changed ? 'updated' : 'unchanged'} ${file}`)
    }
    return
  }

  process.stdout.write(block)
}

main()
