// The API/scripts spec files (design/specs/aimaestro-*-spec.md) are GENERATED by
// scripts/gen-specs.mjs — which, until 2026-08-20, was invoked by NOTHING (the
// checked-in-tooling-nothing-runs class: it reads as automation while the specs silently
// rot against the route/script tree). This guard runs the generator's own --check mode in
// a subprocess: exit 0 = byte-in-sync, exit 1 prints DRIFT lines. The fix for a red here
// is `yarn specs:gen` and committing the result — never editing the spec by hand (the
// files say "GENERATED, do not hand-edit").
import { describe, it, expect } from 'vitest'
import { spawnSync } from 'node:child_process'
import path from 'node:path'

describe('generated specs stay in sync with the tree', () => {
  it('scripts/gen-specs.mjs --check exits 0 (regenerate with `yarn specs:gen` on drift)', () => {
    const root = path.resolve(__dirname, '../..')
    const r = spawnSync(process.execPath, [path.join(root, 'scripts/gen-specs.mjs'), '--check'], {
      cwd: root,
      encoding: 'utf8',
      timeout: 60_000,
    })
    // stdout/stderr surfaced so a red names the drifted file, not just "exit 1"
    expect(r.status, `${r.stdout}\n${r.stderr}`).toBe(0)
    expect(r.stdout).toMatch(/specs in sync/) // positive control: the check RAN (not a crash path)
  })
})
